#!/bin/bash

npm i &&
(cd ./server && npm i) &&
((cd ../swiss-army-knife && git pull) || (cd ../ && git clone https://github.com/fatlard1993/swiss-army-knife.git)) &&
(cd ../swiss-army-knife && ./SETUP) &&
gulp compile &&
ln -s $(pwd)/../swiss-army-knife/client/fonts/ $(pwd)/client/public/fonts